### ISSUE TITLE
Allow cropping trials

### ISSUE THREAD

**Issue by dsaff** [google/science-journal#10]
As mentioned in #4, being able to crop a run would be very useful when the data of interest actually happens after the recording starts or before it ends.  This is on the team's roadmap.

**Comment by berndporr** [comment]
Sounds good!

**Comment by dsaff** [comment]
Give it a try!

- Pull the latest source
- Build and install
- Menu > Testing Options > Enable experimental tools
- Take a recording
- On the trial review screen, choose "Crop" from the overflow menu.

Let us know what you think!

**Comment by berndporr** [comment]
works perfectly:
a) before
![before_crop](https://cloud.githubusercontent.com/assets/1679394/20317928/18546b48-ab60-11e6-8175-601d64890f47.png)
b) during
![during_crop](https://cloud.githubusercontent.com/assets/1679394/20317938/23e10840-ab60-11e6-886a-eaf364a2e104.png)
c) after
![after_crop](https://cloud.githubusercontent.com/assets/1679394/20317947/2a152930-ab60-11e6-9f0a-049a8f733cee.png)
With that feature and the "restart" during recording it's pretty workable for most situations I'd say.

**Comment by dsaff** [comment]
Just pushed a new chunk of commits to github.  Cropping is even better now, when enabled.

**Comment by berndporr** [comment]
![before](https://cloud.githubusercontent.com/assets/1679394/20942107/d545bdfa-bbf1-11e6-90e2-c35d1c79da06.png)
![during](https://cloud.githubusercontent.com/assets/1679394/20942113/db21c7c8-bbf1-11e6-92f9-0375ba79f8a5.png)
![after](https://cloud.githubusercontent.com/assets/1679394/20942116/dfb7551e-bbf1-11e6-8ace-28eff41a3a13.png)
indeed. Looks great. Just connected a signal generator and then slowed down the frequency to 0Hz.

**Comment by dsaff** [comment]
OK, this is good to go in github, and will be live in Play Store at our next release.  Thanks!
