### ISSUE TITLE
Developer options

### ISSUE THREAD

**Issue by CorvetteCole** [google/science-journal#12]
At some point after flashing a custom ROM and kernel science journal allowed me to access the experimental developer settings. This allowed me to use sensors on my phone not otherwise available. At some point I restored to stock and lost these options. I have root and Xposed, is there any way I can activate the developer options again? Is there a flag in the build.prop I can edit? The Moto phones you had at maker faire had access to the experimental sensors so I was hoping you guys could help me out. Thanks.

**Comment by dsaff** [comment]
Are you comfortable building and installing the app from github source?

**Comment by CorvetteCole** [comment]
Yes

**Comment by dsaff** [comment]
If you build the debug flavor, the developer options should be available.  Let me know!

**Comment by CorvetteCole** [comment]
Sounds good! Thanks!
