### ISSUE TITLE
Add delete option for Jornals

### ISSUE THREAD

**Issue by pylang** [google/science-journal#15]
I'd like to remove some temporary journals I made to explore the feature of this app.  The option seems available but grayed out.   Can the option be added to remove journals?

**Comment by dsaff** [comment]
Can you try archiving the projects first?

**Comment by pylang** [comment]
I am not inclined to archive a temporary object, and trying things got me in this situation.  If I archive, will that give the option to delete?  I am unsure of the depth of this rabbit hole...

**Comment by dsaff** [comment]
If you archive, it will make the data invisible in most views, without losing data.  Once you archive, if you want to save space, you can also delete.

**Comment by pylang** [comment]
After archiving, I was given the option to delete.  My issue was resolved, but I submit this procedure was not intuitive.  Typically if something is created, there is a proximal option to quickly undo what was done.   However, if you wish to keep this  behavior, might I suggest a reminder to instruct new users how to delete projects?  Many thanks.
