### ISSUE TITLE
Unable to run app after building on Android Studio

### ISSUE THREAD

**Issue by hermoine1109** [google/science-journal#29]
_I'm using Android Studio 3.0.1 and all necessary plugins have been installed but i get this error every time i try to run it on an AVD or my phone using USB debugging._

Error:(62, 1) A problem occurred evaluating project ':scalarinputapi'.
> Could not read script 'https://raw.githubusercontent.com/ArthurHub/release-android-library/master/android-release-aar.gradle'.
   > raw.githubusercontent.com

_Even after clean building and including necessary packages, the problem persists._

**Comment by hermoine1109** [comment]
Solved.

We need to run the command:
_gradlew clean build generateRelease_
from the android studio terminal.
Also, from the SDK manager, we need to visit SDK updates tab and check the option
_'force https:// sources to be fetched using http://..'_
Uninterrupted internet connection mandatory to apply the mentioned changes.

**Comment by rlogical-techsoft** [comment]
I am also getting one related issue #38 . Would be good if you help me if you have any solution.
