### ISSUE TITLE
'External devices' won't list the sensor names but is fully functional otherwise

### ISSUE THREAD

**Issue by berndporr** [google/science-journal#3]
The "external devices" view looks like this:
![ext_dev_bug](https://cloud.githubusercontent.com/assets/1679394/18814580/8ca38e3a-830f-11e6-8d5f-7a2849c017f7.png)
I've paired three sensors and all the others are also there. I can go back to the main UI and do my experiments with them. There everything works as it should.
In order to get to the bottom of it I've added to ConnectableSensorRegistry:
```
   public void setPairedSensors(PreferenceCategory availableDevices,
            PreferenceCategory pairedDevices, Map<String, ExternalSensorSpec> sensors) {
        for (Map.Entry<String, ExternalSensorSpec> entry : sensors.entrySet()) {
            ExternalSensorSpec sensor = entry.getValue();
            removeSensorWithSpec(availableDevices, sensor);

            ConnectableSensor newSensor = ConnectableSensor.connected(sensor, entry.getKey());
            Preference pref = buildPreference(newSensor, null);
            pref.setWidgetLayoutResource(R.layout.preference_external_device);
            pref.setSummary(sensor.getSensorAppearance().getName(pref.getContext()));
            // bbb
            pref.setTitle("setPairedSensors");
            pref.setSummary("setPairedSensors");
            pairedDevices.addPreference(pref);
        }
```
and
```
    @NonNull
    private Preference makePreference(ConnectableSensor sensor, String key,
            PendingIntent settingsIntent) {
        Preference pref = new Preference(mContext);
        pref.setTitle(sensor.getName());
        pref.setKey(key);
        pref.setSummary("makePreference");
        pref.setTitle("makePreference");
        Log.d(TAG,String.format("make Preference: Title = %s, name = %s",sensor.getName(),key));
        mSettingsIntents.put(key, settingsIntent);
        return pref;
    }
```
still the Preferences are empty. All the calls seem to contain the right Strings and are not empty. I've also followed it through to ManageDevicesFragment but couldn't find any place where Title/Summary might got lost. I'd be happy to continue getting to the bottom of it but would really appreciate your help. I'm puzzled.

**Comment by berndporr** [comment]
Here is a zip of the library where I've added loads of debugging output:
[whistlepunk.zip](https://github.com/google/science-journal/files/491875/whistlepunk.zip)
The zip contains also the debug output (mon.txt, mon2.txt) which I've also attached here:
[mon.txt](https://github.com/google/science-journal/files/491876/mon.txt)
[mon2.txt](https://github.com/google/science-journal/files/491877/mon2.txt)

**Comment by berndporr** [comment]
I should also add the corresponding screenshot when the logs were generated. I clicked on the icon to add more sensors.
![external-devices](https://cloud.githubusercontent.com/assets/1679394/18818033/8f1e16ec-8366-11e6-9fd8-9a8449e966e1.png)

**Comment by dsaff** [comment]
Hmm, let me look into this!

**Comment by dsaff** [comment]
Thank you for the thorough report!

**Comment by dsaff** [comment]
I think somehow the text is suddenly getting written out in white.  Not sure why, but will report back.

**Comment by berndporr** [comment]
Pleasure re the report and thanks for getting on the case so quickly. Looks very likely indeed that it's white text. Works perfectly otherwise.

**Comment by dsaff** [comment]
I believe the most recent push to master should fix the white text bug.  Let me know if it works for you!

**Comment by berndporr** [comment]
![ext_dev-works](https://cloud.githubusercontent.com/assets/1679394/18934479/d6f14f80-85d1-11e6-8011-eba4bc273101.png)
It does! Updated the API calls and it works. Thanks for getting on the case so quickly.
