### ISSUE TITLE
personal science journal - many features still needed!

### ISSUE THREAD

**Issue by cauerego** [google/science-journal#31]
i want to log my life and, later on, analyze it against reality around me. so i was quickly very interested in this app capabilities as there's really nothing like it in the market! but unfortunately, there are still too many missing essential features to be useful for me right now. i believe they wouldn't be too hard to implement since just 2 of them might be enough:

- log all sensor at once
- automatic backup! sync with docs, spreadsheet, keep, ifttt, add an api or something (even if this is or will be on google takeout, i still can't risk the lack of a true automatic backup)
- search (although this might be mitigated by backup, to docs)
- plot graphs (although this also might be mitigated by backup, to spreadsheets)

and then, given i'm doing so many requests in a single issue already, here are a couple more that would be really helpful, even if not essential:

- let us feely set date and time of observation, to log past experiments
- much quicker and practical way to add observations/logs - for instance: through persistent notification or app shortcut a single press will do a pre-configured action to log all sensors and then record audio and/or transcribe it into a text comment

hopefully you can merge a few or all of those features into 1 issue! :D

**Comment by dsaff** [comment]
Hi!

Are you aware that you can snapshot more than one sensor at a time?  Also, automatic backup is coming, please stay tuned!

**Comment by cauerego** [comment]
you mean each one at different snapshots times, right?

if that's the case, perhaps i need to clarify my reasoning why i want them
all at once...

not sure how to deepen it more though. it's just a wish for such a personal
experiment. probably it's even worthless for most people... or perhaps it
might show to be more valuable than it looks, over time.

but if not, if you mean "more than one at the exact same snapshot time"
then i'm clueless how to do it. would you kindly clarify? :)

can't wait to see how the backup will turn out to be!

**Comment by dsaff** [comment]
You should be able to drag a sensor pane up to reveal a plus sign that adds another sensor pane.  You can continue doing that until you've added a pane for every sensor, and then taking a snapshot will snapshot every available sensor.  Make sense?

**Comment by cauerego** [comment]
so sorry i missed that! 💯 

thank you!! 🥇
