### ISSUE TITLE
Failed to load sensor data reported but it works

### ISSUE THREAD

**Issue by berndporr** [google/science-journal#6]
I've recorded a short video (admittedly at a too low bitrate!) but you get the idea:
https://www.youtube.com/watch?v=09uzuLuCyRE&feature=youtu.be
I get the circular spinner when I start the program but if I for example go into the external dev config and back it reports briefly Failed to load sensor data but that then goes away once my service reports the successful connection and everything is fine. I cannot really tell science journal that I'm waiting for a connection explicitly so it seems so that it defaults to the error message or can I use the listener to tell sciencejournal I'm waiting? How can I prevent the error icon and have the spinner back up running?
Please ignore that with two cards I need to restart the program (I'm fixing that at the moment).

**Comment by whatsthebeef** [comment]
@berndporr You could try calling `onSensorConnecting` in `ISensorStatusListener` to inform science journal that you are connecting.

**Comment by berndporr** [comment]
Thanks. I must have overseen the method when trawling through the API. I'll add it.
