### ISSUE TITLE
Exporting of collected data

### ISSUE THREAD

**Issue by martinszy** [google/science-journal#7]
I like that I can use this tool to collect and annotate data. But if I want to export the information I gathered to publish in my science project page for others to analyze, then I'm not able to it.
It's a requirement for a project I'm advising on and this tool was rejected because of that unmet requirement.
Do you think it's something you might add?
Just a CSV of the data for each observation, and the notes as an additional column would work, or maybe something more complex but still using open standards.

**Comment by berndporr** [comment]
Good to have opened that issue to discuss it. Here is my suggestion:
(Google people correct me if I'm wrong) I see Science Journal as an app which is for school kids to offer them an as easy as possible entry into the world of science/STEM which I find just great. In that spirit I'd love to have a "share" button where the user could just e-mail the experiments to their peers and then could be directly opened by them. It would be great to have that as easy as sharing a photo or a meme. I see Science Journal quite distinctively different to a classical data acquisition program (see my comedirecord or Attysplot for example for classical DAQ programs) where everything should be as easy as possible. That's also that I suggested to do some automated scaling for example. I see it as an app which hides away all the nitty gritty like CSV, data formats, etc and shows a fun app where data is directly visualized and stays visualized later on which I see as its main strength. Having said that: a "share" button would be great which exports in a format (XML?) that science journal apps on the peers' phones can open the data transparently like a photo (and for us data geeks we can convert it & import it into our own visualizers like octave, R, matlab, gnuplot, ...). How about this?

**Comment by martinszy** [comment]
I don't mind if it's XML as long as I can share it and convert it. And I
agree with your vision about the use case.

**Comment by scrubskip** [comment]
Hi there!

Export as CSV is already available: it's in the overflow menu (the three dots) in the Trial review screen.

https://productforums.google.com/forum/#!topic/sciencejournal/EWN15E9PyMI;context-place=forum/sciencejournal

Right now it's pretty basic: it just exports the currently selected sensor in CSV with a UNIX timestamp and the value (no notes). However, we already were planning on improving this in an upcoming release.

Please let us know more about any other requirements for your project: hopefully you can use Science Journal for it now!
