### ISSUE TITLE
Artefacts while plotting

### ISSUE THREAD

**Issue by berndporr** [google/science-journal#9]
I've got a strange problem which I think has only shown up with the latest update last week. It's intermittent. I've just managed to catch it.
This is the data I'm sending through via onNewData(Math.round(timestamp),v); here plotted against the timestamp so that you see that there aren't any time-reversals or timestamp issues:
![orig_data](https://cloud.githubusercontent.com/assets/1679394/19480417/341f0eb6-9542-11e6-988f-8fb8bdff7fd7.png)
I've literally had a Log.d directly next to the onNewData with the pairs to be sure I have the exact data:
[log.zip](https://github.com/google/science-journal/files/536484/log.zip)
Now what I see in ScienceJournal are these samples:
![screenshot](https://cloud.githubusercontent.com/assets/1679394/19480491/7796a6c2-9542-11e6-8237-7f0ddec423e4.png)
Any idea from where that might come from? It doesn't matter if I have one or two channels running. It's also intermittent that sometimes it's really bad and sometimes it looks perfect for the whole recording:
![lookingok](https://cloud.githubusercontent.com/assets/1679394/19480672/2c01ba84-9543-11e6-884e-7dd67a5fe2e5.png)
The timestamp is kept pretty close to the system clock (certainly not creating time reversals etc). I do a bit of timestamp correction so that the Attys clock and the system clock are always in sync. I take the Attys sampling interval of 8ms and then do a small correction of the timestamp to stay in sync with the system clock. Of course not going back in time to correct it. The Attys is very precise with its internal clock:
`                    double timeNow = System.currentTimeMillis();
                    // let see if we drift apart which happens because
                    // the clock in the Attys might be slightly
                    // faster or slower
                    // so if the timestamp is lagging behind the
                    // system time we speed up our timestamp a bit
                    double timeDiff = timeNow - timestamp;

```
                // let's gently stay in sync with the system
                // time but let the ADC clock dominate the
                // timing because we know that they arrive at
                // the sampling rate (+/- a small drift)
                double offset = 0.1 * timeDiff / ((double) attysComm.getSamplingRateInHz());

                Log.d(TAG, String.format("offset=%f,timeDiff=%f", offset, timeDiff));

                timestamp = timestamp + samplingInterval + offset;`
```

Happy to do some debugging if you point me to the bit where it's processed.

**Comment by dsaff** [comment]
Thanks for the report, I'm going to do some investigation, and report back.

**Comment by dsaff** [comment]
I've been having some trouble duplicating the error.  Quick question: during the peaks where the value sits at 1.8, what is the sampling rate?  I'm curious if the sampling rate goes down at the peak (since the line looks so smooth), which might lead in an interesting direction.

Thanks!

**Comment by dsaff** [comment]
Also, if you want to see what the timestamps are when they arrive in Science Journal, you could add debugging at https://github.com/google/science-journal/blob/master/OpenScienceJournal/whistlepunk_library/src/main/java/com/google/android/apps/forscience/whistlepunk/api/scalarinput/ScalarInputSensor.java#L92

**Comment by berndporr** [comment]
I haven't seen the bug for a while actually. Annoying in a certain way. The sampling rate is 125Hz for all recordings. Science Journal is not able to plot all samples especially when scrolling over the whole screen but they certainly all show up later when reviewing the recording:
https://youtu.be/M-l7K_AMr-Q
In that recording with the spikes the timestamps perhaps got mixed up. I'll add the debugging as you've suggested and report back asap!

**Comment by berndporr** [comment]
I've saved the data to the log and plotted it with gnuplot. It's all looking good. The data you have seen above was logged directly from onNewData from my side so it should be the same and it is. If I see it again I'll post it here but I'm also not able to re-produce that behaviour again. I've got the inkling it has to do with the screen refresh rate and how samples are dropped. Perhaps on that day I had something in the background which slowed down the program just a little bit but that's just my inkling it could be there. As always: happy to put more debug statements in it and send it over.
[data3.zip](https://github.com/google/science-journal/files/554534/data3.zip)
![data3](https://cloud.githubusercontent.com/assets/1679394/19747045/4701c0d8-9bd1-11e6-869d-ae303d031dd6.png)
```
                @Override
                public void onNewData(long timestamp, double data) {
                    mLatestData = data;
                    mScheduler.unschedule(mRefreshRunnable);
                    mScheduler.schedule(Delay.millis(MINIMUM_REFRESH_RATE_MILLIS),
                            mRefreshRunnable);
                    mConsumer.addData(timestamp, data);
                    Log.d("ScalarInputSensor",String.format("%d %f",timestamp,data));

                    // Some sensors may forget to set to connected, but if we're getting data,
                    //   we're probably connected.  (This actually happened in a version of the
                    //   Vernier implementation.)
                    if (mMostRecentStatus != SensorStatusListener.STATUS_CONNECTED) {
                        mSensorStatusListener.onSensorConnected();
                    }
                }
            }

```

**Comment by berndporr** [comment]
... just to be sure that it's not more timebase corrector: I've introduced different levels of jitter to the timestamps but it still works really robustly. Perhaps the bug has been fixed as a collateral?

**Comment by dsaff** [comment]
Entirely possible, we've been cleaning up that area of the code over the last couple of weeks.  I'll close this; feel free to re-open if you observe it again.  Thanks!
